// 统一的Mock数据文件
// 只包含测试数据，类型定义已移至types.ts

import type { Module, Entity, EnumClass, BehaviorDef } from './types';

// 模块Mock数据
export const MOCK_MODULES: Module[] = [
  {
    id: 'container',
    name: '容器',
    deprecated: false,
    attributes: [
      {
        id: 'container/content',
        type: '(entity:s,type_id:s,type_name:s,flow_min:n,flow_max:n,amount:n,detail:u,cost:n,capacity:n,delivery_rate:n,production_rate:n)[]',
        name: '内容物',
      },
      {
        id: 'container/strategy',
        type: 's',
        name: '策略',
      },
      {
        id: 'container/capacity',
        type: 'n',
        name: '容量',
      },
    ],
  },
  {
    id: 'mobile',
    name: '移动的',
    deprecated: false,
    attributes: [
      {
        id: 'mobile/path',
        type: 'n[6][]',
        name: '路径',
      },
      {
        id: 'mobile/step_path',
        type: 'n[6][]',
        name: '步进路径',
      },
      {
        id: 'mobile/road_path',
        type: 'n[6][]',
        name: '路网路径',
      },
      {
        id: 'mobile/step_road_path',
        type: 'n[6][]',
        name: '路网步进路径',
      },
      {
        id: 'mobile/road_position',
        type: 'n[3][]',
        name: '路网位置',
      },
      {
        id: 'mobile/destination',
        type: 'n[6]',
        name: '目的地',
      },
      {
        id: 'mobile/velocity',
        type: '(mode:s,scalar:n)[]',
        name: '速度',
      },
    ],
  },
  {
    id: 'terrain',
    name: '地形通用',
    deprecated: false,
    attributes: [
      {
        id: 'terrain/landform_matrix',
        type: '(depth:n,elevation:n,composition:(matter:s,amount:n)[])[][]',
        name: '地貌矩阵',
      },
      {
        id: 'terrain/hydrology_matrix',
        type: '(depth:n,elevation:n,velocities:(n:n,w:n,e:n,s:n),flow:n)[][]',
        name: '水文矩阵',
      },
      {
        id: 'terrain/road_network',
        type: '(node:s,position:n[3],neighbors:s[])[]',
        name: '路网',
      },
      {
        id: 'terrain/river_network',
        type: '(node:s,position:n[3],neighbors:s[])[]',
        name: '河网',
      },
    ],
  },
  {
    id: 'controlled',
    name: '可控制的',
    deprecated: false,
    attributes: [
      {
        id: 'controlled/commands',
        type: '(command:s,args:u)[]',
        name: '指令集合',
      },
      {
        id: 'controlled/standby_position',
        type: 'n[3]',
        name: '待机位置',
      },
      {
        id: 'controlled/work_position',
        type: 'n[3]',
        name: '工作位置',
      },
      {
        id: 'controlled/action',
        type: 's',
        name: '行为',
      },
      {
        id: 'controlled/action_cost',
        type: 'n',
        name: '行为消耗',
      },
      {
        id: 'controlled/action_progress',
        type: 'n',
        name: '行为进度',
      },
      {
        id: 'controlled/action_target',
        type: 's',
        name: '行为目标',
      },
      {
        id: 'controlled/stance',
        type: 's',
        name: '姿态',
      },
      {
        id: 'controlled/status',
        type: 's',
        name: '状态',
      },
    ],
  },
  {
    id: 'vehicle',
    name: '载具',
    deprecated: false,
    attributes: [
      {
        id: 'vehicle/loading_area',
        type: 's',
        name: 'loading_area',
      },
      {
        id: 'vehicle/unloading_area',
        type: 's',
        name: 'unloading_area',
      },
      {
        id: 'vehicle/type',
        type: 's',
        name: 'type',
      },
    ],
  },
  {
    id: 'transform',
    name: '变换',
    deprecated: false,
    attributes: [
      {
        id: 'transform/coordinates',
        type: 'n[3]',
        name: '坐标',
      },
      {
        id: 'transform/position',
        type: 'n[3]',
        name: '位置',
      },
      {
        id: 'transform/lonlatposition',
        type: 'n[3]',
        name: '经纬度位置',
      },
      {
        id: 'transform/rotation',
        type: 'n[3]',
        name: '旋转',
      },
      {
        id: 'transform/scale',
        type: 'n[3]',
        name: '缩放',
      },
    ],
  },
];

// 实体Mock数据
export const MOCK_ENTITIES: Entity[] = [
  {
    id: 'vehicle',
    name: '载具',
    deprecated: false,
    attributes: [
      {
        id: 'vehicle_yard_id',
        type: 's',
        name: '集结点id',
      },
      {
        id: 'task_id',
        type: 's',
        name: '任务id',
      },
      {
        id: 'vehicle_name',
        type: 's',
        name: '载具名称',
      },
      {
        id: 'length',
        type: 'n',
        name: '长',
      },
      {
        id: 'width',
        type: 'n',
        name: '宽',
      },
      {
        id: 'height',
        type: 'n',
        name: '高',
      },
      {
        id: 'empty_weight',
        type: 'n',
        name: '空载重量',
      },
      {
        id: 'max_takeoff_weight',
        type: 'n',
        name: '最大起飞重量',
      },
      {
        id: 'max_people_count',
        type: 'n',
        name: '最大运输人数',
      },
      {
        id: 'rotor_diameter',
        type: 'n',
        name: '旋翼直径',
      },
      {
        id: 'tail_rotor_diameter',
        type: 'n',
        name: '尾桨直径',
      },
      {
        id: 'rated_flow',
        type: 'n',
        name: '额定排水流量',
      },
      {
        id: 'rated_head',
        type: 'n',
        name: '额定扬程',
      },
      {
        id: 'pumping_need_min_depth',
        type: 'n',
        name: '抽水所需最低水深',
      },
    ],
    bundles: ['mobile', 'transform', 'controlled', 'container', 'vehicle'],
  },
  {
    id: 'slope',
    name: '边坡',
    deprecated: false,
    attributes: [
      {
        id: 'slope_name',
        type: 's',
        name: '名称',
      },
      {
        id: 'slope_type',
        type: 's',
        name: '区分左右',
      },
      {
        id: 'slope_height',
        type: 'n',
        name: '边坡高度',
      },
    ],
    bundles: ['transform'],
  },
  {
    id: 'debris_flow',
    name: '泥石流',
    deprecated: false,
    attributes: [
      {
        id: 'region',
        type: 'n[]',
        name: '泥石流区域',
      },
      {
        id: 'area',
        type: 'n[]',
        name: '泥石流面积',
      },
      {
        id: 'volume',
        type: 'n',
        name: '泥石流量',
      },
      {
        id: 'state',
        type: 's',
        name: '泥石流状态',
      },
      {
        id: 'type',
        type: 's',
        name: '流域形态',
      },
      {
        id: 'form',
        type: 's',
        name: '物质状态',
      },
    ],
    bundles: [],
  },
  {
    id: 'landslide',
    name: '滑坡体',
    deprecated: false,
    attributes: [
      {
        id: 'landslide_amount',
        type: 'n',
        name: '滑坡量',
      },
      {
        id: 'excavated_volume',
        type: 'n',
        name: '已挖方量',
      },
      {
        id: 'landslide_height',
        type: 'n',
        name: '滑坡体高度',
      },
      {
        id: 'landslide_up_width',
        type: 'n',
        name: '滑坡体上宽',
      },
      {
        id: 'landslide_down_width',
        type: 'n',
        name: '滑坡体底宽',
      },
      {
        id: 'landslide_incline length',
        type: 'n',
        name: '滑坡体斜面长',
      },
      {
        id: 'digger_arr',
        type: 'n[]',
        name: '挖掘机工作点',
      },
    ],
    bundles: ['transform'],
  },
  {
    id: 'barrier_lake',
    name: '堰塞湖',
    deprecated: false,
    attributes: [
      {
        id: 'storage_capacity',
        type: 's',
        name: '储水量/库容',
      },
      {
        id: 'barrierlake_area',
        type: 'n',
        name: '堰塞湖面积',
      },
      {
        id: 'water_depth',
        type: 's',
        name: '水深',
      },
      {
        id: 'water_level',
        type: 's',
        name: '水位',
      },
      {
        id: 'max_water_level',
        type: 'n',
        name: '最高水位',
      },
      {
        id: 'water_level_diff',
        type: 'n',
        name: '上下游水位差',
      },
      {
        id: 'region',
        type: 'n[]',
        name: '堰塞湖区域',
      },
      {
        id: 'barrier_lake_water_depth',
        type: 'n',
        name: '堰塞湖底高程',
      },
      {
        id: 'risk_level',
        type: 'n',
        name: '风险等级',
      },
      {
        id: 'discharging_capacity',
        type: 'n',
        name: '泄流量',
      },
      {
        id: 'flood_discharge_time',
        type: 'n',
        name: '泄洪预估所需时长',
      },
      {
        id: 'barrier_lake_safe_water_level',
        type: 'n',
        name: '堰塞湖安全水位',
      },
      {
        id: 'peak_discharge',
        type: 'n',
        name: '洪峰流量',
      },
      {
        id: 'flood_peak_time',
        type: 'n',
        name: '洪峰时间',
      },
      {
        id: 'downstream_runoff_range',
        type: 'n',
        name: '下游径流范围',
      },
      {
        id: 'warn_range_time',
        type: 'n',
        name: '到达下游居住区警戒范围的时间',
      },
      {
        id: 'inflow',
        type: 'n',
        name: '进水流量',
      },
      {
        id: 'outflow',
        type: 'n',
        name: '出水流量',
      },
    ],
    bundles: [],
  },
];

// 枚举类Mock数据
export const MOCK_ENUM_CLASSES: Record<string, EnumClass> = {
  'vehicle-types': {
    id: 'vehicle-types',
    name: '车辆类型',
    description: '工程车辆分类',
    values: ['推土机', '挖掘机', '装载机', '压路机', '起重机', '混凝土搅拌车', '自卸车'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  colors: {
    id: 'colors',
    name: '颜色',
    description: '常用颜色选项',
    values: ['红色', '蓝色', '绿色', '黄色', '黑色', '白色', '银色', '灰色'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  sizes: {
    id: 'sizes',
    name: '尺寸',
    description: '标准尺寸规格',
    values: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  'vip-levels': {
    id: 'vip-levels',
    name: 'VIP等级',
    description: '客户VIP等级分类',
    values: ['普通会员', '银卡会员', '金卡会员', '白金会员', '钻石会员'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  'fuel-types': {
    id: 'fuel-types',
    name: '燃料类型',
    description: '车辆燃料类型',
    values: ['汽油', '柴油', '电动', '混合动力', '天然气'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  'order-priorities': {
    id: 'order-priorities',
    name: '订单优先级',
    description: '订单处理优先级',
    values: ['低', '普通', '高', '紧急'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  'delivery-methods': {
    id: 'delivery-methods',
    name: '配送方式',
    description: '订单配送方式',
    values: ['标准配送', '快速配送', '次日达', '当日达', '自提'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  brands: {
    id: 'brands',
    name: '品牌',
    description: '商品品牌',
    values: ['苹果', '三星', '华为', '小米', 'OPPO', 'vivo', '一加'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  departments: {
    id: 'departments',
    name: '部门',
    description: '公司部门',
    values: ['技术部', '产品部', '运营部', '市场部', '销售部', '人事部', '财务部'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  positions: {
    id: 'positions',
    name: '职位',
    description: '员工职位',
    values: [
      '初级工程师',
      '中级工程师',
      '高级工程师',
      '技术专家',
      '技术经理',
      '产品经理',
      '项目经理',
    ],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
};

// 函数行为Mock数据 (从真实API更新)
export const MOCK_BEHAVIORS: BehaviorDef[] = [
  {
    id: 'com.gsafety.simulation.behavior.entity.Rain.simulateRain',
    name: 'simulateRain',
    description: 'Rain类的simulateRain方法',
    className: 'Rain',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Rain',
    methodName: 'simulateRain',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateRain方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Tunnel.simulate',
    name: 'simulate',
    description: 'Tunnel类的simulate方法',
    className: 'Tunnel',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Tunnel',
    methodName: 'simulate',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulate方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.UndergroundParking.simulate',
    name: 'simulate',
    description: 'UndergroundParking类的simulate方法',
    className: 'UndergroundParking',
    fullClassName: 'com.gsafety.simulation.behavior.entity.UndergroundParking',
    methodName: 'simulate',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulate方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.RiverNode.riverNodeBehavior',
    name: 'riverNodeBehavior',
    description: 'RiverNode类的riverNodeBehavior方法',
    className: 'RiverNode',
    fullClassName: 'com.gsafety.simulation.behavior.entity.RiverNode',
    methodName: 'riverNodeBehavior',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'riverNodeBehavior方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Breach.init',
    name: 'init',
    description: 'Breach类的init方法',
    className: 'Breach',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Breach',
    methodName: 'init',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'BreachIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'init方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Breach.simulate',
    name: 'simulate',
    description: 'Breach类的simulate方法',
    className: 'Breach',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Breach',
    methodName: 'simulate',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulate方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.contract.Material.vehicleTransfer',
    name: 'vehicleTransfer',
    description: 'Material类的vehicleTransfer方法',
    className: 'Material',
    fullClassName: 'com.gsafety.simulation.behavior.contract.Material',
    methodName: 'vehicleTransfer',
    category: 'contract',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instances',
        type: 'u[]',
        description: 'IList<InstanceIO>',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'vehicleTransfer方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Terrain.init',
    name: 'init',
    description: 'Terrain类的init方法',
    className: 'Terrain',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Terrain',
    methodName: 'init',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'terrain',
        type: 'u',
        description: 'TerrainIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'init方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Terrain.simulate',
    name: 'simulate',
    description: 'Terrain类的simulate方法',
    className: 'Terrain',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Terrain',
    methodName: 'simulate',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'terrain',
        type: 'u',
        description: 'TerrainIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulate方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.before',
    name: 'before',
    description: 'Vehicle类的before方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'before',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'before方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.simulateRescuePersonnel',
    name: 'simulateRescuePersonnel',
    description: 'Vehicle类的simulateRescuePersonnel方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'simulateRescuePersonnel',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateRescuePersonnel方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.simulateStringingEquipment',
    name: 'simulateStringingEquipment',
    description: 'Vehicle类的simulateStringingEquipment方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'simulateStringingEquipment',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateStringingEquipment方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.simulateHelicopter',
    name: 'simulateHelicopter',
    description: 'Vehicle类的simulateHelicopter方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'simulateHelicopter',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateHelicopter方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.helicopterAction',
    name: 'helicopterAction',
    description: 'Vehicle类的helicopterAction方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'helicopterAction',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'helicopterAction方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.simulateDrainDevice',
    name: 'simulateDrainDevice',
    description: 'Vehicle类的simulateDrainDevice方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'simulateDrainDevice',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateDrainDevice方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.drainDeviceAction',
    name: 'drainDeviceAction',
    description: 'Vehicle类的drainDeviceAction方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'drainDeviceAction',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'drainDeviceAction方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.simulateTransport',
    name: 'simulateTransport',
    description: 'Vehicle类的simulateTransport方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'simulateTransport',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateTransport方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.transportAction',
    name: 'transportAction',
    description: 'Vehicle类的transportAction方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'transportAction',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'transportAction方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.simulateBoatBridge',
    name: 'simulateBoatBridge',
    description: 'Vehicle类的simulateBoatBridge方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'simulateBoatBridge',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateBoatBridge方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.boatBridgeAction',
    name: 'boatBridgeAction',
    description: 'Vehicle类的boatBridgeAction方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'boatBridgeAction',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'boatBridgeAction方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.executeTask',
    name: 'executeTask',
    description: 'Vehicle类的executeTask方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'executeTask',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'executeTask方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.simulateDumper',
    name: 'simulateDumper',
    description: 'Vehicle类的simulateDumper方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'simulateDumper',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateDumper方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.dumperAction',
    name: 'dumperAction',
    description: 'Vehicle类的dumperAction方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'dumperAction',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'dumperAction方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.simulateDozer',
    name: 'simulateDozer',
    description: 'Vehicle类的simulateDozer方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'simulateDozer',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateDozer方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.dozerAction',
    name: 'dozerAction',
    description: 'Vehicle类的dozerAction方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'dozerAction',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'dozerAction方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.simulateDigger',
    name: 'simulateDigger',
    description: 'Vehicle类的simulateDigger方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'simulateDigger',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateDigger方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.simulateBarge',
    name: 'simulateBarge',
    description: 'Vehicle类的simulateBarge方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'simulateBarge',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateBarge方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.bargeAction',
    name: 'bargeAction',
    description: 'Vehicle类的bargeAction方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'bargeAction',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'bargeAction方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.simpleMove',
    name: 'simpleMove',
    description: 'Vehicle类的simpleMove方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'simpleMove',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simpleMove方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.moveOnRoad',
    name: 'moveOnRoad',
    description: 'Vehicle类的moveOnRoad方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'moveOnRoad',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'moveOnRoad方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.moveInSky',
    name: 'moveInSky',
    description: 'Vehicle类的moveInSky方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'moveInSky',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'moveInSky方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Vehicle.simulate',
    name: 'simulate',
    description: 'Vehicle类的simulate方法',
    className: 'Vehicle',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Vehicle',
    methodName: 'simulate',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulate方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Scene.init',
    name: 'init',
    description: 'Scene类的init方法',
    className: 'Scene',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Scene',
    methodName: 'init',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'init方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Scene.simulate',
    name: 'simulate',
    description: 'Scene类的simulate方法',
    className: 'Scene',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Scene',
    methodName: 'simulate',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulate方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Dike.init',
    name: 'init',
    description: 'Dike类的init方法',
    className: 'Dike',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Dike',
    methodName: 'init',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'init方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.BarrierLake.simulate',
    name: 'simulate',
    description: 'BarrierLake类的simulate方法',
    className: 'BarrierLake',
    fullClassName: 'com.gsafety.simulation.behavior.entity.BarrierLake',
    methodName: 'simulate',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulate方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.before',
    name: 'before',
    description: 'Task类的before方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'before',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'TaskIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'before方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateIncreaseHeightThickness',
    name: 'simulateIncreaseHeightThickness',
    description: 'Task类的simulateIncreaseHeightThickness方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateIncreaseHeightThickness',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateIncreaseHeightThickness方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateUndergroundParkingDrainage',
    name: 'simulateUndergroundParkingDrainage',
    description: 'Task类的simulateUndergroundParkingDrainage方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateUndergroundParkingDrainage',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateUndergroundParkingDrainage方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateFoundationReinforcement',
    name: 'simulateFoundationReinforcement',
    description: 'Task类的simulateFoundationReinforcement方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateFoundationReinforcement',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'TaskIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateFoundationReinforcement方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateTransmissionLineRestoration',
    name: 'simulateTransmissionLineRestoration',
    description: 'Task类的simulateTransmissionLineRestoration方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateTransmissionLineRestoration',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'TaskIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateTransmissionLineRestoration方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateTransportVehicle',
    name: 'simulateTransportVehicle',
    description: 'Task类的simulateTransportVehicle方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateTransportVehicle',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateTransportVehicle方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulatePluggingClosure',
    name: 'simulatePluggingClosure',
    description: 'Task类的simulatePluggingClosure方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulatePluggingClosure',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulatePluggingClosure方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateImperviousHoldBreath',
    name: 'simulateImperviousHoldBreath',
    description: 'Task类的simulateImperviousHoldBreath方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateImperviousHoldBreath',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateImperviousHoldBreath方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateDangerousRockMass',
    name: 'simulateDangerousRockMass',
    description: 'Task类的simulateDangerousRockMass方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateDangerousRockMass',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'TaskIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateDangerousRockMass方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateBoulderTreatment',
    name: 'simulateBoulderTreatment',
    description: 'Task类的simulateBoulderTreatment方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateBoulderTreatment',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'TaskIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateBoulderTreatment方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulatePersonnelSearch',
    name: 'simulatePersonnelSearch',
    description: 'Task类的simulatePersonnelSearch方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulatePersonnelSearch',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'TaskIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulatePersonnelSearch方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulatePersonnelTransfer',
    name: 'simulatePersonnelTransfer',
    description: 'Task类的simulatePersonnelTransfer方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulatePersonnelTransfer',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'TaskIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulatePersonnelTransfer方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateBoatBridgeTransfer',
    name: 'simulateBoatBridgeTransfer',
    description: 'Task类的simulateBoatBridgeTransfer方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateBoatBridgeTransfer',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'TaskIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateBoatBridgeTransfer方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateRiverDredge',
    name: 'simulateRiverDredge',
    description: 'Task类的simulateRiverDredge方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateRiverDredge',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'TaskIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateRiverDredge方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateRoadRepair',
    name: 'simulateRoadRepair',
    description: 'Task类的simulateRoadRepair方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateRoadRepair',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'TaskIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateRoadRepair方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateBuildWrapHead',
    name: 'simulateBuildWrapHead',
    description: 'Task类的simulateBuildWrapHead方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateBuildWrapHead',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateBuildWrapHead方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateExplode',
    name: 'simulateExplode',
    description: 'Task类的simulateExplode方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateExplode',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateExplode方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateFloodischarge',
    name: 'simulateFloodischarge',
    description: 'Task类的simulateFloodischarge方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateFloodischarge',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateFloodischarge方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateTunnelDrainage',
    name: 'simulateTunnelDrainage',
    description: 'Task类的simulateTunnelDrainage方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateTunnelDrainage',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateTunnelDrainage方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateTowerErection',
    name: 'simulateTowerErection',
    description: 'Task类的simulateTowerErection方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateTowerErection',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'TaskIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateTowerErection方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.task.Task.simulateDig',
    name: 'simulateDig',
    description: 'Task类的simulateDig方法',
    className: 'Task',
    fullClassName: 'com.gsafety.simulation.behavior.entity.task.Task',
    methodName: 'simulateDig',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'TaskIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateDig方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Team.init',
    name: 'init',
    description: 'Team类的init方法',
    className: 'Team',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Team',
    methodName: 'init',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'TeamIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'init方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Team.simulate',
    name: 'simulate',
    description: 'Team类的simulate方法',
    className: 'Team',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Team',
    methodName: 'simulate',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'TeamIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulate方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.MountainRange.init',
    name: 'init',
    description: 'MountainRange类的init方法',
    className: 'MountainRange',
    fullClassName: 'com.gsafety.simulation.behavior.entity.MountainRange',
    methodName: 'init',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'init方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.MountainRange.simulate',
    name: 'simulate',
    description: 'MountainRange类的simulate方法',
    className: 'MountainRange',
    fullClassName: 'com.gsafety.simulation.behavior.entity.MountainRange',
    methodName: 'simulate',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulate方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.DrainDevice.simulate',
    name: 'simulate',
    description: 'DrainDevice类的simulate方法',
    className: 'DrainDevice',
    fullClassName: 'com.gsafety.simulation.behavior.entity.DrainDevice',
    methodName: 'simulate',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulate方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.DangerousRockMass.simulateLandslide',
    name: 'simulateLandslide',
    description: 'DangerousRockMass类的simulateLandslide方法',
    className: 'DangerousRockMass',
    fullClassName: 'com.gsafety.simulation.behavior.entity.DangerousRockMass',
    methodName: 'simulateLandslide',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulateLandslide方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Plan.before',
    name: 'before',
    description: 'Plan类的before方法',
    className: 'Plan',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Plan',
    methodName: 'before',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'plan',
        type: 'u',
        description: 'PlanIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'before方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.Plan.simulate',
    name: 'simulate',
    description: 'Plan类的simulate方法',
    className: 'Plan',
    fullClassName: 'com.gsafety.simulation.behavior.entity.Plan',
    methodName: 'simulate',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'plan',
        type: 'u',
        description: 'PlanIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulate方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.VehicleYard.simulate',
    name: 'simulate',
    description: 'VehicleYard类的simulate方法',
    className: 'VehicleYard',
    fullClassName: 'com.gsafety.simulation.behavior.entity.VehicleYard',
    methodName: 'simulate',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulate方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.MaterialYard.before',
    name: 'before',
    description: 'MaterialYard类的before方法',
    className: 'MaterialYard',
    fullClassName: 'com.gsafety.simulation.behavior.entity.MaterialYard',
    methodName: 'before',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'before方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.MaterialYard.simulate',
    name: 'simulate',
    description: 'MaterialYard类的simulate方法',
    className: 'MaterialYard',
    fullClassName: 'com.gsafety.simulation.behavior.entity.MaterialYard',
    methodName: 'simulate',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulate方法的返回值',
    },
  },
  {
    id: 'com.gsafety.simulation.behavior.entity.WeirBody.simulate',
    name: 'simulate',
    description: 'WeirBody类的simulate方法',
    className: 'WeirBody',
    fullClassName: 'com.gsafety.simulation.behavior.entity.WeirBody',
    methodName: 'simulate',
    category: 'entity',
    parameters: [
      {
        name: 'context',
        type: 'u',
        description: 'Context',
        required: true,
      },
      {
        name: 'instance',
        type: 'u',
        description: 'InstanceIO',
        required: true,
      },
    ],
    returns: {
      type: 'u',
      description: 'simulate方法的返回值',
    },
  },
];
